import { StyleSheet, Dimensions } from "react-native";

const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;
const imageHeight = Dimensions.get("window").height * 0.2;

export const myStyles = (fontSizeIncr = 0) =>
  StyleSheet.create({
    container: {},
    img: {
      width: imageHeight,
      height: imageHeight,
      borderRadius: 10,
      elevation: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4.5,
      alignSelf: "center",
    },
    imgLarge: {
      width: screenWidth,
      height: imageHeight * 2,
      elevation: 4,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4.5,
      alignSelf: "center",
    },
    cellContent: {
      borderRadius: 15,
      width: "100%",
      flexDirection: "row",
      minHeight: imageHeight * 1.25,
      paddingRight: screenWidth / 25,
    },
    textContainer: {
      width: imageHeight / 1.1,
      borderColor: "black",
      marginTop: imageHeight / 6,
      marginLeft: screenWidth / 25,
      justifyContent: "flex-start",
    },
    iconContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    timerText: {
      fontSize: 10 + fontSizeIncr,
    },
    title: {
      fontSize: 16 + fontSizeIncr,
      fontWeight: "bold",
    },
    tagline: {
      fontSize: 12 + fontSizeIncr,
      color: "#888",
    },
    heartContainer: {
      justifyContent: "center",
      alignSelf: "Center",
    },
    heartContainerAlt: {
      position: "absolute",
      alignItems: "center",
      justifyContent: "center",
      right: screenWidth / 25,
      top: screenWidth / 25,
      backgroundColor: "rgba(255,255,255,0.55)",
      padding: 5,
      borderRadius: 30,
      shadowColor: "white",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 3,
    },
    section: {
      marginBottom: screenHeight / 20,
      marginLeft: screenWidth / 25,
      marginRight: screenWidth / 25,
    },
    header: {
      marginTop: screenHeight / 25,
      marginBottom: screenHeight / 40,
      fontWeight: "bold",
      fontSize: 20 + fontSizeIncr,
      textAlign: "center",
      marginVertical: 12,
      textShadowColor: "rgba(0, 0, 0, 0.1)",
      textShadowOffset: { width: 0.75, height: 1 },
      textShadowRadius: 1,
      elevation: 3,
    },
    headerAlt: {
      marginTop: screenHeight / 40,
      marginBottom: screenHeight / 80,
      fontWeight: "bold",
      fontSize: 20 + fontSizeIncr,
      textAlign: "center",
      marginVertical: 12,
      textShadowColor: "rgba(0, 0, 0, 0.1)",
      textShadowOffset: { width: 0.75, height: 1 },
      textShadowRadius: 1,
      elevation: 3,
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#F1F1F1",
      borderColor: "#E2E2E2",
      borderWidth: 1.5,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingLeft: 15,
      height: 50,
      marginBottom: -(screenHeight / 30),
    },
    searchInput: {
      marginLeft: 8,
      flex: 1,
    },
    headerTwo: {
      fontWeight: "bold",
      alignSelf: "center",
      fontSize: 18 + fontSizeIncr,
      marginVertical: 10,
      marginBottom: screenHeight / 35,
    },
    headerTwoAlt: {
      fontWeight: "bold",
      alignSelf: "left",
      fontSize: 18 + fontSizeIncr,
      marginVertical: 10,
      marginBottom: screenHeight / 35,
    },
    homescreenCard: {
      width: screenWidth / 3,
      height: screenHeight / 4,
      backgroundColor: "#f9f9f7",
      borderRadius: 10,
      overflow: "hidden",
      marginRight: 10,
      shadowColor: "#222",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
      marginBottom: 5,
    },
    homescreenCardTextBox: {
      flex: 1,
      padding: 5,
      justifyContent: "flex:start",
    },
    homescreenCardText: {
      fontSize: 12 + fontSizeIncr,
      fontWeight: "bold",
    },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      flexWrap: "wrap",
    },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      gap: 10,
    },
    homescreenButton: {
      backgroundColor: "#E2E2E2",
      borderRadius: 20,
      paddingVertical: 8,
      paddingHorizontal: 10,
      width: screenWidth / 3.7,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#222",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.9,
      shadowRadius: 5,
      elevation: 2,
    },
    recipeInfoCard: {
      backgroundColor: "#f9f9f7",
      borderRadius: 12,
      padding: 15,
      shadowColor: "#222",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 5,
      elevation: 3,
    },
    settingsHeader: {
      fontWeight: "bold",
      color: "black",
      fontSize: 16 + fontSizeIncr,
      marginTop: 30,
      marginBottom: 10,
      marginLeft: screenWidth / 25,
    },
    settingsContainer: {
      backgroundColor: "#f9f9f7",
      borderRadius: 10,
      marginLeft: screenWidth / 25,
      marginRight: screenWidth / 25,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.12,
      shadowRadius: 2,
      elevation: 1,
    },
    settingsItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: "#f9f9f7",
      paddingVertical: 15,
      paddingHorizontal: 15,
      borderBottomWidth: 1,
      borderBottomColor: "#ddd",
    },
    settingsText: {
      fontSize: 16 + fontSizeIncr,
    },
    settingsModalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    settingsModalContent: {
      backgroundColor: "#f9f9f7",
      padding: screenWidth / 25,
      marginLeft: screenWidth / 25,
      borderRadius: 20,
      width: screenWidth / 2.25,
    },
    settingsLogoLarge: {
      alignSelf: "center",
      color: "#C34946",
      fontWeight: "bold",
      marginTop: 10,
      fontSize: 30,
    },
    settingsLogoSmall: { alignSelf: "center", fontSize: 12, marginBottom: 30 },
  });
